import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  container: {
    padding: '0.5rem 0',
  },
  filtersRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    marginBottom: '0.75rem',
  },
  filterInput: {
    minHeight: 44,
    padding: '0.5rem 0.75rem',
    fontSize: '1rem',
    border: '1.5px solid var(--inv-border)',
    borderRadius: 'var(--inv-radius-sm)' as unknown as number,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
    backgroundColor: 'var(--inv-warm-white)',
    color: 'var(--inv-text)',
  },
  filterSelect: {
    minHeight: 44,
    padding: '0.5rem 0.75rem',
    fontSize: '1rem',
    border: '1.5px solid var(--inv-border)',
    borderRadius: 'var(--inv-radius-sm)' as unknown as number,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box' as const,
    backgroundColor: 'var(--inv-warm-white)',
    color: 'var(--inv-text)',
    appearance: 'none' as const,
    textAlign: 'left' as const,
    textAlignLast: 'left' as const,
    cursor: 'pointer',
  },
  toggleRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.5rem',
    marginBottom: '0.75rem',
  },
  lowStockToggle: {
    minHeight: 44,
    minWidth: 44,
    padding: '0.5rem 1rem',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'var(--color-warning-text)',
    backgroundColor: 'var(--inv-amber-light)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-peach)',
    borderRadius: 'var(--inv-radius-full)' as unknown as number,
    cursor: 'pointer',
  },
  lowStockToggleActive: {
    backgroundColor: 'var(--inv-amber)',
    color: 'var(--color-text)',
    borderColor: 'var(--color-warning-text)',
  },
  expiringToggle: {
    minHeight: 44,
    minWidth: 44,
    padding: '0.5rem 1rem',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'var(--color-action)',
    backgroundColor: 'var(--color-sky)',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'var(--color-border)',
    borderRadius: 'var(--inv-radius-full)' as unknown as number,
    cursor: 'pointer',
  },
  expiringToggleActive: {
    backgroundColor: 'var(--color-mint)',
    color: 'var(--color-text)',
    borderColor: 'var(--color-action)',
  },
  emptyText: {
    textAlign: 'center' as const,
    color: 'var(--inv-text-muted)',
    padding: '2rem 0',
  },
  itemsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.625rem',
  },
  card: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.75rem',
    padding: '0.75rem',
    border: '1.5px solid var(--inv-border)',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    backgroundColor: 'var(--inv-warm-white)',
  },
  cardRemoveMode: {
    borderColor: 'var(--inv-primary)',
    backgroundColor: 'var(--inv-primary-bg)',
  },
  thumbnail: {
    width: 48,
    height: 48,
    minWidth: 48,
    borderRadius: 'var(--inv-radius-xs)' as unknown as number,
    backgroundColor: 'var(--color-canvas)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  thumbnailImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
  },
  thumbnailPlaceholder: {
    fontSize: '1.25rem',
  },
  cardBody: {
    flex: 1,
    minWidth: 0,
  },
  cardHeader: {
    flexWrap: 'wrap',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '0.25rem',
  },
  itemName: {
    fontWeight: 600,
    fontSize: '1rem',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
    color: 'var(--inv-text)',
  },
  cardMeta: {
    display: 'flex',
    gap: '0.375rem',
    marginBottom: '0.25rem',
    flexWrap: 'wrap' as const,
  },
  categoryBadge: {
    fontSize: '0.75rem',
    padding: '2px 8px',
    borderRadius: 'var(--inv-radius-full)' as unknown as number,
    backgroundColor: 'var(--inv-category-bg)',
    color: 'var(--inv-category-text)',
  },
  locationBadge: {
    fontSize: '0.75rem',
    padding: '2px 8px',
    borderRadius: 'var(--inv-radius-full)' as unknown as number,
    backgroundColor: 'var(--inv-sage-light)',
    color: 'var(--color-action)',
  },
  cardDetails: {
    flexWrap: 'wrap',
    display: 'flex',
    gap: '1rem',
    fontSize: '0.8125rem',
    color: 'var(--inv-text-muted)',
  },
  expiration: {
    color: 'var(--inv-text-muted)',
  },
  lowStockBadge: {
    fontSize: '0.6875rem',
    fontWeight: 700,
    padding: '2px 6px',
    borderRadius: 'var(--inv-radius-full)' as unknown as number,
    backgroundColor: 'var(--color-danger)',
    color: 'var(--color-danger-text)',
    whiteSpace: 'nowrap' as const,
  },
  removeItemButton: {
    minWidth: 44,
    minHeight: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.125rem',
    color: 'var(--color-danger-text)',
    border: '1px solid var(--color-danger-text)',
    borderRadius: 'var(--inv-radius-xs)' as unknown as number,
    cursor: 'pointer',
  },
  selectionCheckbox: {
    minWidth: 44,
    minHeight: 44,
    accentColor: 'var(--color-danger)',
  },
  notification: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0.75rem 1rem',
    backgroundColor: 'var(--inv-lavender-light)',
    border: '1px solid var(--color-lavender)',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    marginBottom: '0.75rem',
  },
  notificationClose: {
    minWidth: 44,
    minHeight: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'none',
    border: 'none',
    fontSize: '1rem',
    cursor: 'pointer',
    color: 'var(--inv-lavender)',
  },
  categoryCard: {
    minHeight: 44,
    padding: '0.875rem 1rem',
    border: '1.5px solid var(--inv-border)',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    backgroundColor: 'var(--inv-warm-white)',
    cursor: 'pointer',
    userSelect: 'none' as const,
  },
  categoryCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '0.25rem',
  },
  categoryCardName: {
    fontWeight: 600,
    fontSize: '1rem',
    color: 'var(--inv-text)',
  },
  categoryLowStockBadge: {
    fontSize: '0.75rem',
    fontWeight: 600,
    padding: '2px 8px',
    borderRadius: 'var(--inv-radius-full)' as unknown as number,
    backgroundColor: 'var(--color-danger)',
    color: 'var(--color-danger-text)',
  },
  categoryCardStats: {
    flexWrap: 'wrap',
    display: 'flex',
    gap: '0.375rem',
    fontSize: '0.875rem',
    color: 'var(--inv-text-muted)',
  },
  categoryCardDot: {
    color: 'var(--inv-border)',
  },
  categoryGrid: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.625rem',
  },
  backButton: {
    minHeight: 44,
    minWidth: 44,
    padding: '0.5rem 1.25rem',
    fontSize: '0.9375rem',
    fontWeight: 600,
    border: 'none',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    boxShadow: 'var(--inv-shadow-sm)',
    cursor: 'pointer',
    marginBottom: '0.75rem',
    display: 'inline-flex',
    alignItems: 'center',
  },
  groupedRowWrapper: {
    display: 'flex',
    flexDirection: 'column' as const,
  },
  groupedRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
    minHeight: 44,
    padding: '0.875rem 1rem',
    border: '1.5px solid var(--inv-border)',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    backgroundColor: 'var(--inv-warm-white)',
    cursor: 'pointer',
    userSelect: 'none' as const,
  },
  groupedRowChevron: {
    fontSize: '0.875rem',
    lineHeight: '1.4rem',
    color: 'var(--inv-text-muted)',
    minWidth: 16,
  },
  groupedRowBody: {
    flex: 1,
    minWidth: 0,
  },
  groupedRowHeader: {
    flexWrap: 'wrap',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    marginBottom: '0.25rem',
  },
  groupedRowName: {
    fontWeight: 600,
    fontSize: '1rem',
    color: 'var(--inv-text)',
  },
  thresholdButton: {
    marginLeft: 'auto',
    minHeight: 32,
    padding: '0.25rem 0.5rem',
    border: '1px solid var(--inv-border)',
    borderRadius: 6,
    background: 'var(--inv-warm-white)',
    color: 'var(--inv-text-muted)',
    cursor: 'pointer',
  },
  thresholdEditor: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '0.5rem',
    padding: '0.75rem',
    border: '1.5px solid var(--inv-border)',
    borderTop: 'none',
    background: 'var(--inv-warm-white)',
  },
  thresholdInput: {
    width: 90,
    minHeight: 40,
    padding: '0.375rem 0.5rem',
    border: '1.5px solid var(--inv-border)',
    borderRadius: 6,
  },
  thresholdSaveButton: {
    minHeight: 40,
    padding: '0.375rem 0.75rem',
    border: 'none',
    borderRadius: 6,
    background: 'var(--inv-primary)',
    color: 'var(--color-text)',
    cursor: 'pointer',
  },
  thresholdCancelButton: {
    minHeight: 40,
    padding: '0.375rem 0.75rem',
    border: '1px solid var(--inv-border)',
    borderRadius: 6,
    background: 'transparent',
    cursor: 'pointer',
  },
  groupedRowStats: {
    flexWrap: 'wrap',
    display: 'flex',
    gap: '0.375rem',
    fontSize: '0.875rem',
    color: 'var(--inv-text-muted)',
  },
  groupedChildren: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.5rem',
    // Indentation (≥ 16px) relative to the parent grouped row, plus a vertical
    // connector line and a distinct background to set child items apart.
    marginLeft: 12,
    paddingLeft: 20,
    paddingTop: '0.5rem',
    paddingBottom: '0.5rem',
    borderLeft: '2px solid var(--inv-border)',
    backgroundColor: 'var(--inv-surface-alt, var(--color-canvas))',
    borderBottomLeftRadius: 'var(--inv-radius-md)' as unknown as number,
    borderBottomRightRadius: 'var(--inv-radius-md)' as unknown as number,
  },
  groupedChildRow: {
    display: 'flex',
    alignItems: 'center',
    position: 'relative' as const,
  },
  groupedChildConnector: {
    width: 12,
    minWidth: 12,
    height: 2,
    backgroundColor: 'var(--inv-border)',
    marginRight: 4,
    flexShrink: 0,
  },
  groupedChildCard: {
    flex: 1,
    minWidth: 0,
  },
};
