import type React from 'react';
export const styles: Record<string, React.CSSProperties> = {
  centered: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
  },
  errorText: {
    color: 'var(--color-danger-text)',
    fontSize: '1rem',
    marginBottom: '0.75rem',
  },
  retryButton: {
    minWidth: 44,
    minHeight: 44,
    padding: '0.5rem 1.5rem',
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    backgroundColor: 'var(--inv-primary)',
    border: 'none',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    cursor: 'pointer',
    boxShadow: 'var(--inv-shadow-sm)',
  },
  actionRow: {
    display: 'flex',
    gap: '1rem',
    marginBottom: '1rem',
  },
  addButtonWrapper: {
    position: 'relative' as const,
    flex: 1,
  },
  addButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    width: '100%',
    minHeight: 56,
    minWidth: 44,
    padding: '0.75rem 1rem',
    fontSize: '1.125rem',
    fontWeight: 700,
    color: 'var(--color-text)',
    backgroundColor: 'var(--color-mint)',
    border: 'none',
    borderRadius: 'var(--inv-radius-lg)' as unknown as number,
    cursor: 'pointer',
    boxShadow: 'var(--inv-shadow-sm)',
  },
  removeButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.5rem',
    flex: 1,
    minHeight: 56,
    minWidth: 44,
    padding: '0.75rem 1rem',
    fontSize: '1.125rem',
    fontWeight: 700,
    color: 'var(--color-text)',
    backgroundColor: 'var(--color-danger)',
    border: 'none',
    borderRadius: 'var(--inv-radius-lg)' as unknown as number,
    cursor: 'pointer',
    boxShadow: 'var(--inv-shadow-sm)',
  },
  removeButtonActive: {
    backgroundColor: 'var(--color-danger)',
    boxShadow: 'inset 0 2px 4px rgba(0,0,0,0.15)',
  },
  buttonIcon: {
    fontSize: '1.5rem',
    lineHeight: 1,
    fontWeight: 700,
  },
  addMenu: {
    position: 'absolute' as const,
    top: '100%',
    left: 0,
    right: 0,
    marginTop: 4,
    backgroundColor: 'var(--inv-warm-white)',
    border: '1px solid var(--inv-border)',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    boxShadow: 'var(--inv-shadow-md)',
    zIndex: 20,
    overflow: 'hidden',
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    width: '100%',
    minHeight: 48,
    padding: '0.75rem 1rem',
    fontSize: '1rem',
    color: 'var(--inv-text)',
    backgroundColor: 'transparent',
    border: 'none',
    borderBottom: '1px solid var(--inv-border)',
    cursor: 'pointer',
    textAlign: 'left' as const,
  },
  removeModeHint: {
    fontSize: '0.875rem',
    color: 'var(--inv-amber)',
    marginBottom: '0.75rem',
    fontStyle: 'italic',
  },
  // BarcodeScannerLoadingFallback styles
  scannerLoadingOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: '1rem',
  },
  scannerLoadingModal: {
    backgroundColor: 'var(--inv-warm-white)',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    width: '100%',
    maxWidth: 480,
    padding: '2rem 1.25rem',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1rem',
  },
  scannerLoadingSpinner: {
    width: 40,
    height: 40,
    border: '4px solid var(--color-border)',
    borderTopColor: 'var(--inv-primary)',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  scannerLoadingText: {
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    margin: 0,
  },
  // BarcodeScannerErrorBoundary styles
  scannerErrorOverlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 100,
    padding: '1rem',
  },
  scannerErrorModal: {
    backgroundColor: 'var(--inv-warm-white)',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    width: '100%',
    maxWidth: 480,
    padding: '2rem 1.25rem',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '1.25rem',
  },
  scannerErrorText: {
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    margin: 0,
    textAlign: 'center',
  },
  scannerErrorButtons: {
    display: 'flex',
    gap: '0.75rem',
  },
  scannerErrorRetryButton: {
    minHeight: 44,
    minWidth: 44,
    padding: '0.625rem 1.25rem',
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    backgroundColor: 'var(--inv-sage)',
    border: 'none',
    borderRadius: 'var(--inv-radius-md)' as unknown as number,
    cursor: 'pointer',
  },
  scannerErrorCloseButton: {
    minHeight: 44,
    minWidth: 44,
    padding: '0.625rem 1.25rem',
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    backgroundColor: 'var(--color-canvas)',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    cursor: 'pointer',
  },
};
