import type { CSSProperties } from 'react';

export const styles: Record<string, CSSProperties> = {
  page: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100%',
    position: 'relative',
  },
  pageHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    marginBottom: '1rem',
  },
  backButton: {
    minWidth: 44,
    minHeight: 44,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.5rem 0.75rem',
    background: 'none',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    cursor: 'pointer',
    fontSize: '0.9375rem',
    color: 'var(--color-text)',
  },
  pageTitle: {
    fontSize: '1.25rem',
    fontWeight: 700,
    margin: 0,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.25rem',
  },
  label: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'var(--color-text)',
  },
  smallLabel: {
    fontSize: '0.75rem',
    fontWeight: 600,
    color: 'var(--color-secondary)',
  },
  input: {
    minHeight: 44,
    padding: '0.5rem 0.75rem',
    fontSize: '1rem',
    border: '1px solid var(--color-border)',
    borderRadius: 6,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  textarea: {
    padding: '0.5rem 0.75rem',
    fontSize: '1rem',
    border: '1px solid var(--color-border)',
    borderRadius: 6,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    resize: 'vertical',
    fontFamily: 'inherit',
    lineHeight: 1.5,
  },
  fieldError: {
    fontSize: '0.8125rem',
    color: 'var(--color-danger-text)',
  },
  errorBanner: {
    padding: '0.75rem 1rem',
    backgroundColor: 'var(--color-danger)',
    border: '1px solid var(--color-danger)',
    borderRadius: 8,
    color: 'var(--color-danger-text)',
    fontSize: '0.875rem',
    marginBottom: '0.5rem',
  },
  ingredientsHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  ingredientsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.75rem',
  },
  ingredientRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
    padding: '0.75rem',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    backgroundColor: 'var(--color-canvas)',
  },
  ingredientFields: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
  },
  ingredientNameGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.2rem',
  },
  qtyUnitRow: {
    display: 'flex',
    gap: '0.5rem',
  },
  qtyGroup: {
    flex: '0 0 30%',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.2rem',
  },
  unitGroup: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '0.2rem',
  },
  select: {
    minHeight: 44,
    padding: '0.5rem 0.75rem',
    fontSize: '1rem',
    border: '1px solid var(--color-border)',
    borderRadius: 6,
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
    backgroundColor: 'var(--color-surface)',
  },
  removeButton: {
    flexShrink: 0,
    minWidth: 36,
    minHeight: 36,
    padding: '0.25rem',
    fontSize: '0.875rem',
    color: 'var(--color-secondary)',
    backgroundColor: 'transparent',
    border: '1px solid var(--color-border)',
    borderRadius: 6,
    cursor: 'pointer',
    marginTop: '1.25rem',
  },
  addIngredientButton: {
    minHeight: 44,
    padding: '0.5rem 1rem',
    fontSize: '0.9375rem',
    fontWeight: 600,
    color: 'var(--color-action)',
    backgroundColor: 'var(--color-sky)',
    border: '1px solid var(--color-sky)',
    borderRadius: 8,
    cursor: 'pointer',
    alignSelf: 'flex-start',
  },
  actionBar: {
    position: 'fixed',
    bottom: 56,
    left: 0,
    right: 0,
    display: 'flex',
    gap: '0.75rem',
    padding: '0.75rem 1rem',
    backgroundColor: 'var(--color-surface)',
    borderTop: '1px solid var(--color-border)',
    zIndex: 10,
  },
  cancelButton: {
    flex: 1,
    minHeight: 44,
    padding: '0.5rem 1rem',
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    backgroundColor: 'var(--color-canvas)',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    cursor: 'pointer',
  },
  submitButton: {
    flex: 2,
    minHeight: 44,
    padding: '0.5rem 1rem',
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    backgroundColor: 'var(--color-mint)',
    border: 'none',
    borderRadius: 8,
    cursor: 'pointer',
  },
  centered: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
    gap: '1rem',
  },
  timeFieldsRow: {
    display: 'flex',
    gap: '0.75rem',
  },
  portionsScalerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  portionsScalerButton: {
    minWidth: 44,
    minHeight: 44,
    padding: '0.5rem',
    fontSize: '1.25rem',
    fontWeight: 700,
    color: 'var(--color-text)',
    backgroundColor: 'var(--color-canvas)',
    border: '1px solid var(--color-border)',
    borderRadius: 8,
    cursor: 'pointer',
  },
  portionsScalerValue: {
    fontSize: '1rem',
    fontWeight: 600,
    color: 'var(--color-text)',
    minWidth: 80,
    textAlign: 'center' as const,
  },
  instructionRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '0.5rem',
  },
  stepNumber: {
    paddingTop: '0.65rem',
    minWidth: 24,
    fontWeight: 700,
    color: 'var(--color-text)',
  },
  statusText: {
    color: 'var(--color-secondary)',
    fontSize: '0.9375rem',
    margin: 0,
  },
  errorText: {
    color: 'var(--color-danger-text)',
    fontSize: '0.9375rem',
    margin: 0,
  },
};
